Added in the check for libc-client by creating a new macro
git-svn-id: https://trac.beirdo.ca:4443/svn/beirdobot/trunk@308 c66dcb5a-e80b-0410-ab0e-bb6a4f3ddef9

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -3182,6 +3182,11 @@ MYSQL_LIBS=${ac_cv_mysql_libs}
 
 
 
+
+
+# AC_CHECK_LIB
+
+
 # Check whether --enable-plugin-dns or --disable-plugin-dns was given.
 if test "${enable_plugin_dns+set}" = set; then
   enableval="$enable_plugin_dns"
@@ -3628,6 +3633,85 @@ cat >>confdefs.h <<\_ACEOF
 #define PLUGIN_MAILBOX 1
 _ACEOF
 
+
+echo "$as_me:$LINENO: checking for mail_status in -lc-client" >&5
+echo $ECHO_N "checking for mail_status in -lc-client... $ECHO_C" >&6
+if test "${ac_cv_lib_c_client_mail_status+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+  ac_check_lib_save_LIBS=$LIBS
+LIBS="-lc-client  $LIBS"
+cat >conftest.$ac_ext <<_ACEOF
+/* confdefs.h.  */
+_ACEOF
+cat confdefs.h >>conftest.$ac_ext
+cat >>conftest.$ac_ext <<_ACEOF
+/* end confdefs.h.  */
+char mm_expunged, mm_diskerror, mm_lsub, mm_flags, mm_fatal,
+                     mm_nocritical, mm_notify, mm_searched, mm_status, mm_login,
+	 	     mm_list, mm_critical, mm_exists, mm_log, mm_dlog;
+/* Override any gcc2 internal prototype to avoid an error.  */
+#ifdef __cplusplus
+extern "C"
+#endif
+/* We use char because int might match the return type of a gcc2
+   builtin and then its argument prototype would still apply.  */
+char mail_status ();
+int
+main ()
+{
+mail_status ();
+  ;
+  return 0;
+}
+_ACEOF
+rm -f conftest.$ac_objext conftest$ac_exeext
+if { (eval echo "$as_me:$LINENO: \"$ac_link\"") >&5
+  (eval $ac_link) 2>conftest.er1
+  ac_status=$?
+  grep -v '^ *+' conftest.er1 >conftest.err
+  rm -f conftest.er1
+  cat conftest.err >&5
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } &&
+	 { ac_try='test -z "$ac_c_werror_flag"			 || test ! -s conftest.err'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; } &&
+	 { ac_try='test -s conftest$ac_exeext'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; }; then
+  ac_cv_lib_c_client_mail_status=yes
+else
+  echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+ac_cv_lib_c_client_mail_status=no
+fi
+rm -f conftest.err conftest.$ac_objext \
+      conftest$ac_exeext conftest.$ac_ext
+LIBS=$ac_check_lib_save_LIBS
+fi
+echo "$as_me:$LINENO: result: $ac_cv_lib_c_client_mail_status" >&5
+echo "${ECHO_T}$ac_cv_lib_c_client_mail_status" >&6
+if test $ac_cv_lib_c_client_mail_status = yes; then
+  cat >>confdefs.h <<_ACEOF
+#define HAVE_LIBC_CLIENT 1
+_ACEOF
+
+  LIBS="-lc-client $LIBS"
+
+else
+  { { echo "$as_me:$LINENO: error: libc-client not installed" >&5
+echo "$as_me: error: libc-client not installed" >&2;}
+   { (exit 1); exit 1; }; }
+fi
+LIBS=$ac_check_lib_save_LIBS
 
 fi
 
